controllers/main.py
from flask import render_template
from models.users import User
from models.category import Category

from controllers.cart import show_order
from flask_login import current_user

#צפייה בעמוד ראשי
def main():
    categories = Category.query.all()
    loged=current_user.is_authenticated 
    if not loged:
        greeting = 'אורח'
    else:
        greeting = f'{current_user.first_name.capitalize()} { current_user.last_name.capitalize()}'
        
    return render_template('after_login/main.html',greeting=greeting,categories=categories,loged=loged,show_order=show_order())
    



        

routes/main.py
from controllers.main import main
from flask import Blueprint
main_bp = Blueprint('main',__name__)

main_bp.add_url_rule('/',view_func=main)

templates/after_login/change_details.html
{% extends 'layouts/layout.html' %}{% block content %}
<form method="POST" action="{{url_for('users.change_details')}}" novalidate class="card-panel">
    {{form.csrf_token}}
    <div>
        <div>{{form.first_name.label}}</div>
        <div>{{form.first_name(value=user.first_name)}}</div>
        {% for message in form.first_name.errors %}
        <div style="color: red">{{message}}</div>
        {% endfor %}
    </div>
    <div>
        <div>{{form.last_name.label}}</div>
        <div>{{form.last_name(value=user.last_name)}}</div>
        {% for message in form.last_name.errors %}
        <div style="color: red">{{message}}</div>
        {% endfor %}
    </div>
    <div>
        {% with not_avalible = get_flashed_messages(category_filter=['not_avalible']) %}
        {% if not_avalible %}
            {% for message in not_avalible %}
            <div class="card-panel red ">{{message}}</div>
            {%endfor%}
            {%endif%}
            {% endwith %}
        <div>{{form.username.label}}</div>
        <div>{{form.username(value=user.username)}}</div>
        {% for message in form.username.errors %}
        <div style="color: red">{{message}}</div>
        {% endfor %}
    </div>
    <div>
        <div>{{form.password.label}}</div>
        <div>{{form.password(value=user.password)}}</div>
        {% for message in form.password.errors %}
        <div style="color: red">{{message}}</div>
        {% endfor %}
    </div>
    <div>
        <div>{{form.confirm_password.label}}</div>
        <div>{{form.confirm_password(value=user.confirm_password)}}</div>
        {% for message in form.confirm_password.errors %}
        <div style="color: red">{{message}}</div>
        {% endfor %}
    </div>
    <div>
        <div>{{form.email.label}}</div>
        <div>{{form.email(value=user.email)}}</div>
        {% for message in form.email.errors %}
        <div style="color: red">{{message}}</div>
        {% endfor %}
    </div>
    <div>
        <div>{{form.address.label}}</div>
        <div>{{form.address(value=user.carts[-1].deliveries.address)}}</div>
    </div>
    <div>{{form.submit1}}</div>
</form>
{% endblock %}

templates/after_login/dishes_by_category.html
{% extends 'layouts/layout.html' %}{% block content %}
<section>

    <div class="right-align border-bottom"><h2>{{category.name}}</h2></div><br>
    <div class="row " >
        {% for dish in dishes %}
         <div class="col s3 right-align">
          <div class="card grey lighten-3">
            <div class="card-image ">
              <img  class="" src="{{dish.imageUrl}}">
          </div class="row ">
          <span class="card-title">{{dish.name}}</span>
          <div >
              <div >קטגוריה: {{dish.categories.name}}</div>
              <div >מחיר: {{dish.price}}₪</div>
              <p >:תיאור<br>  {{dish.description}}  
                {%if dish.is_gluten_free%}
              <div>ללא גלוטן</div>
              {%endif%}
              {% if dish.is_vegeterian%}
              <div>טבעוני</div>
              {%endif%}</p>
              
            </div>
            <form
            action="{{url_for('cart.add_to_cart',id=dish.id)}}"
            novalidate
            method="POST"
          >
          {{form.csrf_token}}
            <div class="card-action">
              <div class="center-align">
                {{form.amount.label}} {{form.amount(value=1)}} {{form.submit1}}
                {% for message in form.amount.errors %}
                <div style="color: red">{{message}}</div>
                {% endfor %}
              </div>
            </div>
          </form>
          </div>
        </div>
        {%endfor%}
  
</section>
{% endblock %}

templates/after_login/main.html
{% extends 'layouts/layout.html' %}{% block content %} {% with success =
get_flashed_messages(category_filter=['success']) %} {% if success %} {% for
message in success %}
<div class="card-panel light-green">{{message}}</div>
{% endfor %} {% endif %} {% endwith %}

{% with details_changed =
  get_flashed_messages(category_filter=['details_changed']) %} {% if details_changed %} {% for
  message in details_changed %}
  <div class="card-panel light-green">{{message}}</div>
  {% endfor %} {% endif %} {% endwith %}

  {% with added = get_flashed_messages(category_filter=['added']) %}
  {% if added %}
  {% for message in added %}
  <div class="card-panel light-green ">{{message}}</div>
  {%endfor%}
  {%endif%}
  {% endwith %}

  {% with details_not_changed =
    get_flashed_messages(category_filter=['details_not_changed']) %} {% if details_not_changed %} {% for
    message in details_not_changed %}
    <div class="card-panel red">{{message}}</div>
    {% endfor %} {% endif %} {% endwith %}

<div style="margin: 10px">
  <div><h4>שלום! {{greeting}}</h4></div>
</div>

<div class="row">
  <div class="col s6">
    <h3 class="right-align border-bottom">קטגוריות</h3>
  </div>
  <div class="col s6">
    <h3 class="right-align border-bottom">העגלה שלי</h3>
  </div>
</div>

<div class="row">
  <div class="col s12 m6">
    <div class="row">
      {% for category in categories %}
      <a href="{{url_for('categories.dishes_by_category',id=category.id)}}">
        <div class="col s12 m6">
          <div class="hoverable card grey lighten-3">
            <div class="card-image">
              <img src="{{category.imageUrl}}" />
            </div>
            <div class="center-align">
              <span class="card-title" style="text-decoration: none"
                >{{category.name}}</span
              >
            </div>
            <div>
              <div class="center-align">
                <a
                  class="waves-effect light-blue btn"
                  href="{{url_for('categories.dishes_by_category',id=category.id)}}"
                  >היכנס</a
                >
              </div>
            </div>
          </div>
        </div></a
      >
      {% endfor %}
    </div>
  </div>
  <div class="col s12 m6">
    {% if loged %}
    <div class="collection">
      {% for item in show_order %}
      <a
        href="{{url_for('dishes.show_dish',id=item.dishes.id)}}"
        class="collection-item"
        >{{item.dishes.name}}
        <img
          style="max-width: 50px; max-height: 50px"
          src="{{item.dishes.imageUrl}}"
          alt=""
          class="circle"
      /></a>
      {%endfor%} {%else%}
      <div class="card-panel"><h6>לצפייה בעגלה התחבר</h6></div>
      <div>
        <a class="hoverable waves-effect light-blue btn" href="{{url_for('users.login')}}"
          >התחבר</a
        >
      </div>
      {%endif%}
    </div>
  </div>

</div>
  {% endblock %}

templates/after_login/order_confirm.html
{% extends 'layouts/layout.html' %}{% block content %}
<div class="card-panel right-align">
    <div class="right-align"><h2>!הזמנה בוצעה בהצלחה</h2></div>
    <div><h4>{{delivery.id}} :הזמנה מספר</h4></div>
    <div><h5>{{delivery.cart.deliveries.created}} :תאריך הזמנה</h5></div>
    {%if delivery.is_deliverd %}
    <div>סטטוס הזמנה: נשלח </div>
    {%else%}
    <div>סטטוס הזמנה: בהכנה </div>
    {%endif%}
    <div>
        <table class="responsive-table">
            <thead>
                <tr>
                    <th>שם מנה</th>
                    <th>מחיר</th>
                </tr>
            </thead>
            {% for item in delivery.cart.items%}
            <tbody>
              <tr>
                <td>{{item.dishes.name}}</td>
                <td>{{item.dishes.price}}₪</td>
              </tr>
            </tbody>
            {%endfor%}
        </table>
        <h5>שולם:{{cart_price}}₪</h5>
    </div>
    
</div>
{% endblock %}

templates/after_login/order_form.html
{% extends 'layouts/layout.html' %}{% block content %}
<form action="{{url_for('deliveries.order_form',id = delivery.id)}}" novalidate method="POST">
    {{form.csrf_token}}
<div class="card-panel">
  <div>
    <div>{{form.address.label}}</div>
    <div>{{form.address(value=delivery.address)}}</div>
    {% for message in form.address.errors %}
    <div style="color: red">{{message}}</div>
    {% endfor %}
  </div>
  <div>
    <div>{{form.comment.label}}</div>
    <div>{{form.comment(value=delivery.comment)}}</div>
  </div>
  <div>{{form.submit4}}</div>
</div>
</form>
{% endblock %}

templates/after_login/order_history.html
{% extends 'layouts/layout.html' %}{% block content %}

<h3>היסטוריית הזמנות</h3>
{% for cart in range(len(carts))[::-1] %} 
{%if len(carts[cart].items) > 0 %}
<ul class="collection with-header">
  <li class="collection-header"><h4>מספר הזמנה: {{carts[cart].id}}</h4></li>
  {% if not carts[cart].deliveries.created == None %}
  <li class="collection-header">
    <h5>תאריך:{{carts[cart].deliveries.created}}</h5>
    {%else%}
    <li class="collection-header"><h5>תאריך:הזמנה לא בוצעה עדיין</h5></li>
    {%endif%}
  {% if carts[cart].deliveries.is_delivered %}
   <li class="collection-item"><h6>סטטוס הזמנה: נשלח</h6></li>
   {%else%}
   <li class="collection-item"><h6>סטטוס הזמנה: <span style="font-weight: 900;">**בהכנה</span></h6></li>
   {%endif%}
  </li>
  
   {%for item in carts[cart].items%}

  <li class="collection-item">{{item.dishes.name}}|{{item.dishes.price}}₪</li>
  {%endfor%}
  {% if carts[cart].deliveries.is_delivered %}
  <li><h6>שולם:{{sum(price[cart])}}₪</h6></li>
  {%else%}
  <li><h6>סכום לתשלום:{{sum(price[cart])}}₪</h6></li>
  {%endif%}
</ul>
{%endif%} {%endfor%} {%endblock%}

templates/after_login/show_cart.html
{% extends 'layouts/layout.html' %}{% block content %}
<div>
  <div class="right-align"><h2>עגלת קניות</h2></div>
  <div class="left-align">
    {% if cart_price > 0 %}
    <div>
      <a
        class="hoverable waves-effect btn"
        href="{{url_for('deliveries.order_form',id=cart_id)}}"
        >לביצוע הזמנה</a
      >
      סכום לתשלום:{{cart_price}}₪
    </div>
    {%endif%}
    
  </div>
</div>
<div style="max-height: min-content" class="collection card-panel">
  {% for item in current_cart %}
  <div class="collection-item">
    <a href="{{url_for('dishes.show_dish',id=item.dishes.id)}}">
      <img
        style="max-width: 50px; max-height: 50px"
        src="{{item.dishes.imageUrl}}"
        alt=""
        class="circle"
      />
      <div class=""><h6>{{item.dishes.name}}</h6></div></a
    >
    <div>מחיר:{{item.dishes.price}}₪</div>
    <div>תיאור:{{item.dishes.description}}</div>

    <div class="left-align">
      <a
        class="waves-effect light-blue btn"
        href="{{url_for('cart.delete_item_from_cart',id=item.dishes.id)}}"
        >מחיקה</a
      ><a class="waves-effect light-blue btn">עריכה</a>
    </div>
  </div>
  {%endfor%}
</div>

{% endblock %}

templates/after_login/show_categories.html
{% extends 'layouts/layout.html' %}{% block content %}
    <div class="right-align border-bottom"><h2>קטגוריות</h2></div>
      <div class="row">
        {% for category in categories %}
        <a href="{{url_for('categories.dishes_by_category',id=category.id)}}">
          <div class="col s12 m3">
          <div class="card grey lighten-3">
            <div class="card-image">
              <img src="{{category.imageUrl}}" />
            </div>
            <div class="center-align"><span class="card-title" style="text-decoration: none;">{{category.name}}</span></div>
            <div>
              <div class="center-align "><a class="hoverable waves-effect light-blue btn" href="{{url_for('categories.dishes_by_category',id=category.id)}}">היכנס</a></div>
            </div>
          </div>
        </div></a>
        {% endfor %}
      </div>

{% endblock %}

templates/after_login/show_dish.html
{% extends 'layouts/layout.html' %}{% block content %}
<div class="row">
  <div class="col s6"></div>
  <div class="col s6">
    <div class="card-panel lighten-3">
      <div class="card-image">
        <img
          style="max-width: 300px; max-height: 300px"
          class="container"
          src="{{dish.imageUrl}}"
        />
      </div>
      <h5 class="card-title"> {{dish.name}}</h5>
      <div>
        <div>קטגוריה: {{dish.categories.name}}</div>
        <div>מחיר: {{dish.price}}₪</div>
        <p>
          :תיאור<br />
          {{dish.description}}
        </p>
        {%if dish.is_gluten_free%}
        <div>ללא גלוטן</div>
        {%endif%} {% if dish.is_vegeterian%}
        <div>טבעוני</div>
        {%endif%}
        <a class="hoverable waves-effect light-blue btn" href="{{url_for('main.main')}}"
          >חזרה לעמוד הראשי</a
        >
        <a class="hoverable waves-effect light-blue btn" href="{{url_for('cart.add_to_cart',id=dish.categories.id)}}"
          >הוספה לעגלה</a
        >
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/after_login/show_dishes.html
{% extends 'layouts/layout.html' %}{% block content %}
<div class="right-align border-bottom"><h2>מנות</h2></div>
<div class="row">
  {% for dish in dishes %}
  <div class="col s12 m3 right-align">
    <div class="card grey lighten-3">
      <div class="card-image">
        <img class="" src="{{dish.imageUrl}}" />
      </div>
      <span class="card-title">{{dish.name}}</span>
      <div>
        <div>קטגוריה: {{dish.categories.name}}</div>
        <div>מחיר: {{dish.price}}₪</div>
        <p>
          :תיאור<br />
          {{dish.description}}
        </p>
        {%if dish.is_gluten_free%}
        <div>ללא גלוטן</div>
        {%endif%} {% if dish.is_vegeterian%}
        <div>טבעוני</div>
        {%endif%}
      </div>
      <form
      action="{{url_for('cart.add_to_cart',id=dish.id)}}"
      novalidate
      method="POST"
    >
    {{form.csrf_token}}
      <div class="card-action">
        <div class="center-align">
          {{form.amount.label}} {{form.amount(value=1)}} {{form.submit1}}
          {% for message in form.amount.errors %}
          <div style="color: red">{{message}}</div>
          {% endfor %}
        </div>
      </div>
    </form>
    </div>
  </div>
  {%endfor%}
</div>
{% endblock %}